/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bartlomiejpluta.samplegame;

import com.bartlomiejpluta.samplegame.core.engine.GameEngine;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class App implements ApplicationRunner {
    private final GameEngine gameEngine;

    @Override
    public void run(ApplicationArguments args) {
        gameEngine.start();
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
