app:
  project:
    main-file: project.bep
    resource-path: /project

  sprite:
    entity:
      dimension:
        rows: 4
        cols: 4

      default-sprite-column: 0

      sprite-direction-rows:
        down: 0
        left: 1
        right: 2
        up: 3