app:
  project:
    main-file: project.bep
    resource-path: /project
    database-script-file: /database/data.sql

  sprite:
    character:
      default-sprite-column: 0

      sprite-direction-rows:
        down: 0
        left: 1
        right: 2
        up: 3