app:
  window:
    title: "Simple Game"
    width: 640
    height: 480

  core:
    targetUps: 50 # Updates per second

  sprite:
    entity:
      dimension:
        rows: 4
        cols: 4

      default-sprite-column: 0

      sprite-direction-rows:
        down: 0
        left: 1
        right: 2
        up: 3


logging:
  level:
    com.bartlomiejpluta.base.core.profiling.time.aspect.ExecutionTimeAspect: DEBUG